# Generated by Django 4.2.4 on 2023-10-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('PickupPoint', models.CharField(max_length=100)),
                ('PickupDate', models.DateField()),
                ('PickupTime', models.CharField(max_length=100)),
                ('EstimatedPrice', models.CharField(max_length=100)),
                ('EstimatedRideTime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('DateOfBirth', models.DateField()),
                ('phone', models.BigIntegerField(max_length=10)),
                ('photo', models.CharField(max_length=250)),
                ('lisence', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('upi', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('languagesknown', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNumber', models.CharField(max_length=100)),
                ('VehicleModelname', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=250)),
                ('PollusionCertificate', models.CharField(max_length=100)),
                ('rc', models.CharField(max_length=100)),
                ('Insurance', models.CharField(max_length=100)),
                ('NumberOfSeats', models.IntegerField()),
                ('VehicleType', models.CharField(max_length=100)),
                ('MinimumWagePerHour', models.CharField(max_length=100)),
                ('DRIVERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('DateOfBirth', models.DateField()),
                ('phone', models.BigIntegerField(max_length=10)),
                ('photo', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.login')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('SubscriptionAmount', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('DRIVERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfSeats', models.CharField(max_length=100)),
                ('VaccantSeats', models.CharField(max_length=100)),
                ('VEHICAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RidePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.booking')),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.users')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Review', models.CharField(max_length=200)),
                ('Rating', models.CharField(max_length=200)),
                ('DRIVERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.drivers')),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.users')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lattitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.users')),
            ],
        ),
        migrations.AddField(
            model_name='drivers',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.login'),
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Complaints', models.CharField(max_length=200)),
                ('Reply', models.CharField(max_length=200)),
                ('ComplaintStatus', models.CharField(max_length=200)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.users')),
            ],
        ),
        migrations.CreateModel(
            name='BookingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OtpVerifiaction', models.CharField(max_length=10)),
                ('OtpDate', models.DateField()),
                ('OtpTime', models.CharField(max_length=20)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='SEATS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.seats'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USERS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.users'),
        ),
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Review', models.CharField(max_length=200)),
                ('Rating', models.CharField(max_length=200)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.users')),
            ],
        ),
    ]
