# Generated by Django 4.2.4 on 2023-10-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Velo_Go', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='Status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
