# Generated by Django 4.2.6 on 2023-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Velo_Go', '0002_drivers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
