# Generated by Django 4.2.4 on 2023-12-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Velo_Go', '0003_alter_drivers_phone_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='lisence',
            field=models.CharField(max_length=300),
        ),
    ]
