# Generated by Django 4.2.4 on 2024-01-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Velo_Go', '0004_alter_drivers_lisence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lattitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Drivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velo_Go.drivers')),
            ],
        ),
    ]
